// Add your functions and code here
function destructivelyAppendKitten(array){kittens.push()
function destructivelyPrependKitten
function destructivelyRemoveLastKitten
function destructivelyRemoveFirstKitten
function appendKitten
function prependKitten
function removeLastKitten
function removeFirstKitten